// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRexB2wKyqM8El7asZ8F3mzx49zcClgBE',
    appId: '1:771001308136:web:c57d36f87a5ff700be8a5d',
    messagingSenderId: '771001308136',
    projectId: 'mich-emergency-response-app',
    authDomain: 'mich-emergency-response-app.firebaseapp.com',
    storageBucket: 'mich-emergency-response-app.firebasestorage.app',
    measurementId: 'G-9M2QQ430FT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZRV4wxEEJkBdrKuqwclyhUK6HS5iamTQ',
    appId: '1:771001308136:android:7d23e022bb97fc39be8a5d',
    messagingSenderId: '771001308136',
    projectId: 'mich-emergency-response-app',
    storageBucket: 'mich-emergency-response-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwgDvYoxmZDUJiderROO6O0-hApglPpk8',
    appId: '1:771001308136:ios:aa856b33583cc1a0be8a5d',
    messagingSenderId: '771001308136',
    projectId: 'mich-emergency-response-app',
    storageBucket: 'mich-emergency-response-app.firebasestorage.app',
    iosClientId: '771001308136-qouaak7n49clel5hj9dtcie5qna02ajm.apps.googleusercontent.com',
    iosBundleId: 'com.example.emergencyResponseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwgDvYoxmZDUJiderROO6O0-hApglPpk8',
    appId: '1:771001308136:ios:aa856b33583cc1a0be8a5d',
    messagingSenderId: '771001308136',
    projectId: 'mich-emergency-response-app',
    storageBucket: 'mich-emergency-response-app.firebasestorage.app',
    iosClientId: '771001308136-qouaak7n49clel5hj9dtcie5qna02ajm.apps.googleusercontent.com',
    iosBundleId: 'com.example.emergencyResponseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRexB2wKyqM8El7asZ8F3mzx49zcClgBE',
    appId: '1:771001308136:web:169b57cd50d78333be8a5d',
    messagingSenderId: '771001308136',
    projectId: 'mich-emergency-response-app',
    authDomain: 'mich-emergency-response-app.firebaseapp.com',
    storageBucket: 'mich-emergency-response-app.firebasestorage.app',
    measurementId: 'G-9XNP9E41N5',
  );

}